[theme]
primaryColor = "#1e3d59"        # Main color for buttons, links, etc.
backgroundColor = "#ffffff"     # Background color of the app
secondaryBackgroundColor = "#f0f0f5"  # Background for widgets
textColor = "#31333F"           # Main text color
font = "sans serif"             # Choose from: sans serif, serif, monospace

# You can add more options, like successColor, warningColor, and more, depending on your need.
